apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: wg-easy
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ui.host }}
      http:
        paths:
          - backend:
              service:
                name: wg-easy-http
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ui.host }}
      secretName: wg-easy-tls
