ingress-nginx:
  controller:
    service:
      type: NodePort
      internal:
        # needs to match server ip in zerotier
        clusterIP: 10.147.20.107
      nodePorts:
        http: 31080
        https: 31443
        tcp:
          22: 31022
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
