ingress-nginx:
  controller:
    service:
      type: NodePort
      ports:
        http: 31080
        https: 31443
      targetPorts:
        http: http
        https: https
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
